# Generated by Django 4.2.3 on 2023-08-16 03:42

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_invoice_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_zip',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_dat',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 21, 42, 37, 186737)),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+1', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+1', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+1', max_length=128, region=None),
        ),
    ]
