# Generated by Django 4.2.3 on 2023-08-16 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_invoice_due_dat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_state',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_zip',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_dat',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 7, 56, 48, 264462)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='other_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
