# Generated by Django 4.2.3 on 2023-08-16 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_gallery_description_alter_invoice_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_dat',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 8, 0, 15, 480522)),
        ),
    ]
