# Generated by Django 4.2.3 on 2023-08-16 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_invoice_due_dat_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_address',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_city',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_state',
            field=models.CharField(blank=True, default=' ', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_zip',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 8, 32, 18, 462287)),
        ),
    ]
